services:
  db:
    image: pgvector/pgvector:pg16
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_DB: hibiz
      POSTGRES_USER: hibiznet
      POSTGRES_PASSWORD: 'hibiz1234!'
    ports:
      - "5433:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
